version: '3.4'

services:
  # redis:
  #   image: redis:latest
  #   container_name: gameclub_redis
  #   restart: always
  #   volumes:
  #     - ./gameclub_redis_data:/data
  #   ports:
  #     - "6379:6379"

  # redis_insight:
  #   image: redislabs/redisinsight:latest
  #   container_name: gameclub_redis_insight
  #   restart: always
  #   ports:
  #     - "8001:8001"
  #   volumes:
  #     - ./gameclub_redis_insight_data:/db
 
  sqldata:
    container_name: microservices-sqldata
    volumes:
      - ./db:/var/opt/mssql/data
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      - SA_PASSWORD=YourStrong@Passw0rd
      - ACCEPT_EULA=Y
    networks:
      - backend
    ports:
      - 6767:1433

  gameclub.api:
    image: ${DOCKER_REGISTRY-}gameclubapi
    build:
      context: .
      dockerfile: src/GameClub/GameClub.API/Dockerfile
    networks:
      - backend
    depends_on:
      - sqldata
      #- redis

  kindergarten.api:
    image: ${DOCKER_REGISTRY-}kindergartenapi
    build:
      context: .
      dockerfile: src/Kindergarten/Kindergarten.API/Dockerfile
    networks:
      - backend
    depends_on:
      - sqldata

  nikoh.api:
    image: ${DOCKER_REGISTRY-}nikohapi
    build:
      context: .
      dockerfile: src/Nikoh/Nikoh.API/Dockerfile
    networks:
      - backend
    depends_on:
      - sqldata

  gateway.api:
    image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: .
      dockerfile: src/GateWay/Gateway.API/Dockerfile
    networks:
     - backend
    ports:
     - 7676:8080

# volumes:
#   redis_volume_data:
#   redis_insight_volume_data:

  jwtservice.api:
    image: ${DOCKER_REGISTRY-}jwtserviceapi
    build:
      context: .
      dockerfile: src/Auth/JwtService.API/Dockerfile
    networks:
     - backend

networks:
  backend:

